FROM mcr.microsoft.com/windows/nanoserver:1809

COPY ./estafette-extension-bitbucket-status.exe c:/estafette-extension-bitbucket-status.exe

ENV ESTAFETTE_LOG_FORMAT="console"

USER ContainerAdministrator

ENTRYPOINT ["C:/estafette-extension-bitbucket-status.exe"]